export const popularFood = [
  {
    id: 1,
    title: 'Hyderabadi Biryani',
    price: 7.50,
    rating: 4.8,
    reviews: 1050,
    deliveryTime: '20 min delivery',
    distance: '2.5 km',
    calories: '450 Cal',
    diameter: '15.05 Cm',
    imagePlaceholder: 'Hyderabadi Veg Biryani 2.png',
    description: 'Hyderabadi biryani is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender meat, and fragrant basmati rice. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......'
  },
  {
    id: 2,
    title: 'Bombay Biryani',
    price: 9.50,
    rating: 5.0,
    reviews: 1200,
    deliveryTime: '25 min delivery',
    distance: '3.5 km',
    calories: '480 Cal',
    diameter: '16.05 Cm',
    imagePlaceholder: 'images (1) 2.png',
    description: 'Bombay biryani is a delicious blend of spices and tender meat that tantalizes the senses with its aromatic spices.'
  },
  {
    id: 3,
    title: 'onion capsicum pizza',
    price: 10.50,
    rating: 4.9,
    reviews: 1550,
    deliveryTime: '20 min delivery',
    distance: '2.5 km',
    calories: '480 Cal',
    diameter: '18.05 Cm',
    imagePlaceholder: 'paneer-pizza 2.png',
    description: 'Onion capsicum pizza is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender onion and capsicum and fragrant pizza base. originating from the vibrant city of the Hyaderabad in India, this is iconic dish......'
  },
  {
    id: 4,
    title: 'Panner pizza',
    price: 9.50,
    rating: 4.2,
    reviews: 1130,
    deliveryTime: '25 min delivery',
    distance: '3.5 km',
    calories: '460 Cal',
    diameter: '12.05 Cm',
    imagePlaceholder: 'paneer-pizza 1.png',
    description: 'Panner and mater pizza is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,mater and tragrant pizza base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......'
  },
  {
    id: 5,
    title: 'Veg Burger',
    price: 12.50,
    rating: 4.2,
    reviews: 1130,
    deliveryTime: '20 min delivery',
    distance: '2.5 km',
    calories: '560 Cal',
    diameter: '6.05 Cm',
    imagePlaceholder: 'images 2.png',
    description: 'Veg burger is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender aalu tiki and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......'
  },
  {
    id: 6,
    title: 'Paneer Burger',
    price: 8.50,
    rating: 4.6,
    reviews: 1230,
    deliveryTime: '25 min delivery',
    distance: '3.5 km',
    calories: '460 Cal',
    diameter: '4.00 Cm',
    imagePlaceholder: 'images 2.png',
    description: 'Panner burger is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu tiki and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......'
  },
  {
    id: 7,
    title: 'Veg Sandwhic',
    price: 7.50,
    rating: 4.6,
    reviews: 1230,
    deliveryTime: '20 min delivery',
    distance: '2.5 km',
    calories: '460 Cal',
    diameter: '4.00 Cm',
    imagePlaceholder: 'veg-sandwich.png',
    description: 'Veg sandwhic is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......'
  },
  {
    id: 8,
    title: 'Potato Sandwhic',
    price: 6.50,
    rating: 4.6,
    reviews: 1343,
    deliveryTime: '25 min delivery',
    distance: '3.5 km',
    calories: '460 Cal',
    diameter: '4.00 Cm',
    imagePlaceholder: 'potato-sandwich.png',
    description: 'Potato sandwhic is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......'
  }
];
